import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ScrollAnimation from './components/scrollAnimation'
import CasestudiesDetails from './components/caseStudiesDetails'
import Banner from './components/banner'
import TopnavBar from './components/topnavbar'
import FoundersDesk from './components/foundersDesk'
import Services from './components/services'
import Casestudies from './components/casestudies'
import Testimonials from './components/testimonials'
import Contacts from './components/contacts'
import './styles/styles.css';
import CustomCursor from './components/customCursor'
import Clients from './components/clients'
import Carousel from './components/carousel'
import Footer from './components/footer'
import VeractDetails from './components/veractDetails'
import './styles/mediaQuery.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'veract',
  description: 'Generated by veract',
}

export default function RootLayout({

  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <CasestudiesDetails /> */}
        <div id="Home">
          <div className=" custom-cursor">
            <CustomCursor />
            <div className="mainPage fontFamily flex">
              <TopnavBar />
              <Banner />
            </div>
            <div>
              <Clients />
            </div>
            <div  >
              <FoundersDesk />
            </div>
            <div >
              <Services />
            </div>
            <div  >
              <Casestudies />
            </div>
            <div >
              <Testimonials />
            </div>
            <div>
              <Contacts />
            </div>
            <div>
              {/* <Carousel/> */}
              < VeractDetails />
            </div>
            <div>
              < Footer />
            </div>
          </div>
        </div>
        {/* <BouncingBall /> */}
        {children}</body>
    </html>
  )
}
