'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/styles.css';
import './styles/mediaQuery.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'veract',
  description: 'Generated by veract',
}



export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        {children}</body>
    </html>
  )
}
