const mobileCustomerSuccess = 
[
    {
        id: 'content1',
        title:"EdTech",
        activeIcon:"/caseStudies/edTech_icon.svg",
        inActiveIcon:"/caseStudies/edtech_icon_gray.svg",
        caseTitle: 'AI-enabled EdTech platform',
        caseTitleContent: 'Evo11ve is an EdTech platform that revolutionizes augmented learning.',
        caseImage: '/caseStudies/mobile_Evo11ve.svg',
        challenges: 'A custom-built, voice-to-text enabled personalized AI coach',
        solution: 'Veract team designed and Developed a desktop app with integrated voice-to-text functionality.Implemented noise cancellation features.Included chat capabilities.',
        services: ['Software architecture', 'Technology consulting', 'Front end development', 'Back end development', 'Deployment'],
        platform: ['Desktop', 'Web'],
        techstack: ['Next JS','Express JS','Electron','Node JS','MongoDB','Elastic Search'],
        clientSpeakName: "",
        clientSpeakCmp: "",
        clientSpeakDesc: "",
    },
    {
        id: 'content2',
        title:"Machine Vision",
        activeIcon:"/caseStudies/machine_icon_blue.svg",
        inActiveIcon:"/caseStudies/mechine_vision_icon.svg",
        caseTitle: 'Automated Machine Vision Inspection',
        caseTitleContent: 'A sheet metal pressings manufacturing company.',
        caseImage: '',
        challenges: 'Over 5 million pieces of parts must go through a comprehensive visual inspection each month. Hand inspection was tedious and, as inspector fatigue set in, accuracy levels dropped.',
        solution: 'Veract created a proprietary AI-powered visual inspection tool to increase productivity and stop problems with part rejections and recalls later on. For the manufacturer, the solution was a complete success due to its cost-effectiveness.',
        services: ['Software architecture','Technology consulting','Software development','Deployment','End to end vision systems'],
        platform: ['Web'],
        techstack: ['Python','Tensorflow','keras','Pytorch'],
        clientSpeakName: "",
        clientSpeakCmp: "",
        clientSpeakDesc: "",
    },
    {
        id: 'content3',
        title:"Wellness",
        activeIcon:"/caseStudies/wellness_icon_blue.svg",
        inActiveIcon:"/caseStudies/wellness_icon.svg",
        caseTitle: 'Health and Wellness Tech',
        caseTitleContent: 'Anyo is a health and wellness app that addresses the significant issue of mental health.',
        caseImage: '/caseStudies/mobile_wellness.svg',
        challenges: 'The founders of Anyo were looking for a one-stop shop for technical advice and development for their live chat-enabled platform with streaming audio, video along with chatbots.',
        solution: 'Within five months, Veract\’s team of architects and developers created their four online portals and the Anyo mobile app making crucial choices on architecture, framework etc.',
        services: ['Software architecture','Technology consulting','Software development','Deployment'],
        platform: ['Mobile','Web'],
        techstack: ['Flutter','Angular','LoopBack'],
        clientSpeakName: "",
        clientSpeakCmp: "",
        clientSpeakDesc: "",
    },
    {
        id: 'content4',
        title:"Industrial Platform",
        activeIcon:"/caseStudies/social_icon_blue.svg",
        inActiveIcon:"/caseStudies/social_icon_gray.svg",
        caseTitle: 'Data Center Innovation Platform',
        caseTitleContent: 'Data Center Mart is an initiative of IBITS.',
        caseImage: '/caseStudies/DataCenter_img.svg',
        challenges: 'Challenged with creating a comprehensive platform tailored specifically for the data center industry including post content, comment, like, and share within the community, with a integrated marketplace for products and services and a directory of suppliers specializing in data center solutions.',
        solution: 'Designed and deployed a web and responsive app.',
        services: ['Design Software architecture','Technology consulting' ,'Front end development','Back end development','Deployment'],
        platform: ['Web'],
        techstack: ['Next JS','Mongo DB','Node JS'],
        clientSpeakName: "",
        clientSpeakCmp: "",
        clientSpeakDesc: "",
    },
    {
        id: 'content5',
        title:"Manufacturing",
        activeIcon:"/caseStudies/manufacturing_icon.svg",
        inActiveIcon:"/caseStudies/manuf_icon_gray.svg",
        caseTitle: 'Quality Documentation for Metal Foundry',
        caseTitleContent: 'An automated quality report generation system for Grey Iron and Ductile Iron Foundry.',
        caseImage: '',
        challenges: 'Submission of parts necessitates the submission of high-quality documentation on spectrometer readings, pouring properties, mould properties and sand properties.',
        solution: 'A one-stop shop that combines machine maintenance, defect prediction, CAPA follow-up, test certificate and other quality documents.',
        services: ['Software architecture','Technology consulting' ,'Software development','Deployment'],
        platform: ['Web'],
        techstack: ['Bootstrap','Express.js','MongoDB','IndexedDB','Redis',
            'jQuery',
           ' Google APIs'],
        clientSpeakName: "",
        clientSpeakCmp: "",
        clientSpeakDesc: "",
    },
    {
        id: 'content6',
        title:"AgriTech",
        activeIcon:"/caseStudies/agriTech_icon.svg",
        inActiveIcon:"/caseStudies/agriTech_icon_gray.svg",
        caseTitle: 'Agriculture Finance Ecosystem',
        caseTitleContent: 'Agrosperity KiVi is a phygital platform in the area of agri supply chain and financing.',
        caseImage: '',
        challenges: 'KiVi was seeking a development partner to fully assume responsibility for the design, development and implementation of Vision to text, Map interfaces for loan eligibility data, loan documents automation, dashboards with multiple authentication levels.',
        solution: 'Veract architects set up the platform and assumed complete ownership of the product and made critical choices of architecture, framework to enable rapid development.',
        services: ['Software architecture','Technology consulting' ,'Software development','Deployment'],
        platform: ['Progressive Web'],
        techstack: ['Java',
            'Spring Boot',
            'PostgreSQL',
            'Nginx',
            'Kafka','Elasticsearch',
            'Google APIs',
            'CI/CD',
            'Angular',
            'Kibana'],
        clientSpeakName: "SALIL NAIR - CTO",
        clientSpeakCmp: "AGROSPERITY TECH SOLUTIONS",
        clientSpeakDesc: "We engaged with Veract team from an early stage and they helped build out our \‘KiViStar\’ App from basic day one concept. Their choice of architechture, framework and ability to deliver the product helped us go to market quickly. This helped us focus on our core work.",
    },
    {
        id: 'content7',
        title:"Ecommerce",
        activeIcon:"/caseStudies/eCom_icon_blue.svg",
        inActiveIcon:"/caseStudies/ecom_icon.svg",
        caseTitle: 'E-Commerce for Seasonal Produce',
        caseTitleContent: 'Beanstalk Farmers operates in the exciting farm-to-table space.',
        caseImage: '/caseStudies/eCom.svg',
        challenges: 'Payment enabled e-commerce site in time for customers produce season.',
        solution: 'Veract team developed and deployed a payment enabled custom designed web application.',
        services: ['Software architecture','Technology consulting' ,'Frontend development','Backend Development','Deployment'],
        platform: [' Web'],
        techstack: ['Next JS', 'Express JS', 'Node JS', 'Redis','PostgreSQL','Razorpay'],
        clientSpeakName: "",
        clientSpeakCmp: "",
        clientSpeakDesc: "",
    },
    {
        id: 'content8',
        title:"Sales",
        activeIcon:"/caseStudies/sales_icon.svg",
        inActiveIcon:"/caseStudies/sales_icon_gray.svg",
        caseTitle: 'Sales Enquiry and Quote Management',
        caseTitleContent: 'Rajdeep is a distributor of industrial products with multiple principals, multiple products, in multiple locations.',
        caseImage: '/output/sales.png',
        challenges: 'Salesman attrition, inconsistent data, quotation production and reporting were the client’s pain concerns. Customer was searching for a solution that would operate with SAP integration and fit into their usual routine.',
        solution: 'Veract created a mobile and online application that seamlessly integrated with the customers existing software.',
        services: ['Software architecture','Technology consulting' ,'Software Development','Deployment'],
        platform: ['Mobile','Web'],
        techstack: ['Bootstrap',
            'Express.js',
            'IndexedDB',
            'MongoDB','Redis',
            'JQuery',
            'Google APIs'],
        clientSpeakName: "ANAND SHAH - DIRECTOR",
        clientSpeakCmp: "RAJDEEP INDUSTRIAL PRODUCTS",
        clientSpeakDesc: "Excellent prompt support inspite of remote location.",
    },
    {
        id: 'content9',
        title:"Audit",
        activeIcon:"/caseStudies/audit_icon_blue.svg",
        inActiveIcon:"/caseStudies/audit_icon.svg",
        caseTitle: 'Data Extraction for the Audit Industry',
        caseTitleContent: 'Financial audit firm with over 100 associates',
        caseImage: '',
        challenges: 'Audit firm looking to reduce manual data entry processes required for compliance.',
        solution: 'Audit firm looking to reduce manual data entry processes required for compliance.',
        services: ['Software architecture','Technology consulting' ,'Frontend development','Backend Development','Deployment'],
        platform: ['Web'],
        techstack: ['Python','Next JS', 'Fast API'],
        clientSpeakName: "",
        clientSpeakCmp: "",
        clientSpeakDesc: "",
    },
    {
        id: 'content10',
        title:"Fintech",
        activeIcon:"/caseStudies/finTech_icon_blue.svg",
        inActiveIcon:"/caseStudies/fintech_icon.svg",
        caseTitle: 'Credit Risk Assessment and Risk Profiling',
        caseTitleContent: 'Northern Arc Capital  is a financial services platform that was established primarily to meet various credit needs of businesses and households that are underserved.',
        caseImage: '',
        challenges: 'For the construction of their investor portal, Northern Arc Capital required a team with technical and financial domain experience. They needed to reduce risk by using risk analytics, risk profiles, etc.',
        solution: 'Veract implemented risk profiling in their investor tracking portal by fusing their core development skills with their expertise in financial domain.',
        services: ['Software architecture','Technology consulting' ,'Software Development','Deployment'],
        platform: ['Web'],
        techstack: ['Angular','Node JS', 'SpringBoot','Kibana','PostgreSQL','ElasticSearch' ],
        clientSpeakName: "",
        clientSpeakCmp: "",
        clientSpeakDesc: "",
    },
    {
        id: 'content11',
        title:"Thermal Vision",
        activeIcon:"/caseStudies/thermal_blue_icon.svg",
        inActiveIcon:"/caseStudies/thermal_gray_icon.svg",
        caseTitle: 'Infrared thermography',
        caseTitleContent: 'The Institute of Buffalo Science focuses on improving buffalo health monitoring by tracking key parameters and mapping udder thermal profiles to detect early onset of mastitis in dairy animals.',
        caseImage: '/caseStudies/Thermal_img.svg',
        challenges: 'Integration of the thermal imaging camera with the monitoring system and IOT. Ensuring real-time data capture and processing.Compatibility between the camera hardware and software solutions.Reliable data transfer protocols to minimize latency.',
        solution: 'VSoftware Development: Created custom software for real-time analysis and visualization of udder thermal profiles and camera control through a user-friendly interface.',
        services: ['Software architecture','Technology consulting' ,'Frontend development','Backend Development','Deployment'],
        platform: ['Web'],
        techstack: ['Dotnet',
            'Angular',
            'MongoDB',' Express.js',
           ' Node.js',
            'Windows'],
        clientSpeakName: "",
        clientSpeakCmp: "",
        clientSpeakDesc: "",
    },
]

export default mobileCustomerSuccess